#!/bin/bash
# Fixture-driven smoke test. Runs without the 97 MB upstream artifact.
#   tests/smoke.sh            # convert + validate XML
#   tests/smoke.sh --build    # also compile a real .dictionary (macOS + DDK)
set -euo pipefail

cd "$(dirname "$0")/.."
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
XML="$WORK/Open Dictionary.xml"

# Stand in for scripts/fetch_audio.py: two clips for `knot`, US-only for
# `abate`, nothing for `chef` — so the fixture covers a full pair, a half pair
# and a headword the source has no recording for. Same split as the real
# fetcher: only OtherResources/ is bundle-bound, the manifest sits outside it.
AUDIO="$WORK/audio"
CLIPS="$AUDIO/OtherResources"
mkdir -p "$CLIPS/Audio/3f" "$CLIPS/Audio/a1"
printf 'ID3fake-uk-clip-padding-to-clear-the-min-size-check%.0s' 1 2 3 4 5 6 7 8 9 10 \
  > "$CLIPS/Audio/3f/knot-3f000001_uk.mp3"
cp "$CLIPS/Audio/3f/knot-3f000001_uk.mp3" "$CLIPS/Audio/3f/knot-3f000001_us.mp3"
cp "$CLIPS/Audio/3f/knot-3f000001_uk.mp3" "$CLIPS/Audio/a1/abate-a1000002_us.mp3"
printf 'knot\tAudio/3f/knot-3f000001_uk.mp3\tAudio/3f/knot-3f000001_us.mp3\n' > "$AUDIO/manifest.tsv"
printf 'abate\t\tAudio/a1/abate-a1000002_us.mp3\n' >> "$AUDIO/manifest.tsv"

echo "==> convert fixture (no audio)"
python3 src/build_appledict.py tests/fixture.jsonl -o "$XML" --source-tag smoke

echo "==> xml is well-formed"
xmllint --noout "$XML"

echo "==> content assertions"
python3 - "$XML" <<'PY'
import sys
x = open(sys.argv[1], encoding="utf-8").read()

def check(name, cond):
    print(f"  {'ok  ' if cond else 'FAIL'} {name}")
    if not cond:
        sys.exit(1)

check("attribution front matter present", "front_back_matter" in x and "CC BY-SA 4.0" in x)
check("converter version stamped", "generated by build_appledict " in x and "转换工具" in x)
check("headword indexed", '<d:index d:value="knot"' in x)
check("inflection indexed at lower priority", 'd:value="knots"' in x and 'd:priority="2"' in x)
check("US/UK pronunciations split", "UK /nɒt/" in x and "US /nɑt/" in x)
check("no audio markup without a manifest", 'class="audio"' not in x)
check("bilingual example rendered", "在绳子上打个结" in x)
check("all-rare entry falls back to full render", "gallimaufry" in x)
check("entry without meanings dropped", "emptyword" not in x)
# The contract pins top-level fields only; sub-object shapes must degrade, not crash.
check("loose forms shape parsed", "tacks" in x)
check("loose pronunciation shape parsed", "/tæk/" in x)
check("loose relation shape parsed", "pin" in x)
# One stray control character makes the whole 310 MB document unparseable,
# and escaping does not help — they are illegal as raw codepoints. Fixture
# en-ctrlchar-01 mirrors the single U+0014 that upstream v2.0 carries.
import re
invalid = re.compile(
    "[^\u0009\u000a\u000d\u0020-\ud7ff\ue000-\ufffd\U00010000-\U0010ffff]"
)
check("no characters illegal in XML 1.0", not invalid.search(x))
check("control-char entry still rendered", "厨师" in x)
# Upstream marks a nonexistent form with "-"; indexing it yields a null search
# key (the DDK skips it noisily) and displaying it yields a bare dash.
check("placeholder form not indexed", 'd:value="-"' not in x)
check("real form alongside it still indexed", 'd:value="abandoned"' in x)
PY

echo "==> priority filter"
python3 src/build_appledict.py tests/fixture.jsonl -o "$WORK/core.xml" --min-priority core --no-front-matter
grep -q "树瘤" "$WORK/core.xml" && { echo "  FAIL rare sense leaked through --min-priority core"; exit 1; }
grep -q "gallimaufry" "$WORK/core.xml" || { echo "  FAIL all-rare entry must survive filtering"; exit 1; }
echo "  ok   rare senses filtered, all-rare entry retained"

echo "==> bundled audio variant"
XMLA="$WORK/Open Dictionary Audio.xml"
python3 src/build_appledict.py tests/fixture.jsonl -o "$XMLA" --source-tag smoke \
  --audio-manifest "$AUDIO/manifest.tsv"
xmllint --noout "$XMLA"
python3 - "$XMLA" <<'PY'
import re, sys
x = open(sys.argv[1], encoding="utf-8").read()

def check(name, cond):
    print(f"  {'ok  ' if cond else 'FAIL'} {name}")
    if not cond:
        sys.exit(1)

check("front matter advertises bundled audio", "含发音（3 条）" in x)
check("both clips rendered for a full pair",
      'href="Audio/3f/knot-3f000001_uk.mp3"' in x and 'href="Audio/3f/knot-3f000001_us.mp3"' in x)
# Half the headwords upstream ships have only one accent, or none at all; a
# button that plays nothing is worse than no button.
entry = re.search(r'<d:entry id="e_en-abate-01".*?</d:entry>', x, re.S).group(0)
check("half pair renders only the accent that exists",
      'abate-a1000002_us.mp3' in entry and 'class="say uk"' not in entry)
check("headword absent from the manifest gets no button", x.count('class="audio"') == 2)
# Relative to Contents/Resources/ — Dictionary.app's WebView has no network
# access, so a remote URL here would fail with MEDIA_ERR_SRC_NOT_SUPPORTED.
check("no remote audio references", "http://" not in x.split("</d:entry>")[1] and "dictvoice" not in x)
# The player is parked on window: an Audio referenced only by a local can be
# collected while play() is still loading the clip.
check("player survives the click handler", "w._dp" in x)
# Dictionary.app parses stored bodies as HTML, where an attribute value is
# entity-decoded but a <script> body is not; keep the handler entity-free.
for attr in re.findall(r'onclick="([^"]*)"', x):
    check("click handler free of entities", "&" not in attr and "<" not in attr)
PY

echo "==> audio manifest is optional"
python3 src/build_appledict.py tests/fixture.jsonl -o "$WORK/mute.xml" --no-front-matter
grep -q 'class="audio"' "$WORK/mute.xml" && { echo "  FAIL audio markup without a manifest"; exit 1; }
echo "  ok   no manifest, no audio markup"

if [[ "${1:-}" == "--build" ]]; then
  echo "==> compile .dictionary"
  [[ -d ddk ]] || git clone --depth 1 -q https://github.com/nanoskript/dictionary-development-kit ddk
  chmod +x ddk/bin/*
  DDK=$(cd ddk && pwd)
  # build_dict.sh copies OtherResources with BSD `cp -XRf`; a coreutils cp
  # earlier in PATH fails the whole build, so pin the system tools here too.
  DDK_ENV=(env PATH=/usr/bin:/bin:/usr/sbin:/sbin)
  "${DDK_ENV[@]}" DICT_DEV_KIT_OBJ_DIR="$WORK/objects" "$DDK/bin/build_dict.sh" -v 10.11 \
    "Open Dictionary" "$XML" src/OpenDictionary.css src/OpenDictionary.plist
  BUNDLE="$WORK/objects/Open Dictionary.dictionary/Contents"
  for f in Info.plist Resources/Body.data Resources/KeyText.data Resources/KeyText.index \
           Resources/EntryID.index Resources/DefaultStyle.css; do
    test -s "$BUNDLE/$f" || { echo "  FAIL missing Contents/$f"; exit 1; }
  done
  grep -q front_back_matter "$BUNDLE/Info.plist" \
    || { echo "  FAIL front matter reference lost"; exit 1; }
  test -d "$BUNDLE/Resources/Audio" && { echo "  FAIL plain build picked up clips"; exit 1; }
  echo "  ok   bundle complete"

  # The audio variant compiles from a staging dir whose OtherResources points
  # at the clip tree — that indirection is the part worth testing, because a
  # silently skipped copy yields a bundle full of dead play buttons.
  echo "==> compile .dictionary (bundled audio)"
  STAGE="$WORK/stage"
  mkdir -p "$STAGE"
  ln -sfn "$CLIPS" "$STAGE/OtherResources"
  ( cd "$STAGE" && "${DDK_ENV[@]}" DICT_DEV_KIT_OBJ_DIR="$WORK/objects-audio" \
      "$DDK/bin/build_dict.sh" -v 10.11 "Open Dictionary" "$XMLA" \
      "$OLDPWD/src/OpenDictionary.css" "$OLDPWD/src/OpenDictionary.plist" )
  BUNDLE_A="$WORK/objects-audio/Open Dictionary.dictionary/Contents"
  test -s "$BUNDLE_A/Resources/Body.data" || { echo "  FAIL audio bundle incomplete"; exit 1; }
  clips=$(find "$BUNDLE_A/Resources/Audio" -name '*.mp3' 2>/dev/null | wc -l | tr -d ' ')
  [[ "$clips" == "3" ]] || { echo "  FAIL expected 3 clips in the bundle, found $clips"; exit 1; }
  # The DDK copies OtherResources wholesale, so build bookkeeping kept in the
  # same tree would ship to users — the manifest lives outside it for that reason.
  test -e "$BUNDLE_A/Resources/manifest.tsv" \
    && { echo "  FAIL manifest leaked into the bundle"; exit 1; }
  echo "  ok   bundle carries $clips clips and no build bookkeeping"
fi

echo "==> smoke passed"
