# Generated by scripts/update_cask.py — do not edit by hand.
cask "open-dictionary-audio" do
  version "2.0"
  sha256 "e55c6f0cdd2809da8c9c196a0df1f224f73b46d0428d13306aa3ebd7c4257bec"

  url "https://github.com/wesleyel/opendict-apple/releases/download/appledict-v#{version}/OpenDictionary-audio.dictionary.zip",
      verified: "github.com/wesleyel/opendict-apple/"
  name "Open Dictionary with Audio"
  name "Open Dictionary 英汉学习词典（含发音）"
  desc "English-Chinese learner dictionary for Dictionary.app, with bundled pronunciation"
  homepage "https://github.com/wesleyel/opendict-apple"

  livecheck do
    url :url
    regex(/^appledict[._-]v?(\d+(?:\.\d+)+)$/i)
    strategy :github_latest
  end

  depends_on macos: :catalina

  conflicts_with cask: "open-dictionary"

  dictionary "Open Dictionary.dictionary"

  caveats <<~EOS
    Dictionary data is CC BY-SA 4.0, derived from Wiktionary via
    github.com/ahpxex/open-dictionary. Enable it in Dictionary.app > Settings.

    Pronunciation clips are bundled, so playback works offline. The
    play buttons need JavaScript, which Dictionary.app supports but the
    three-finger lookup popover does not.
  EOS
end
