# Generated by scripts/update_cask.py — do not edit by hand.
cask "open-dictionary" do
  version "2.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/wesleyel/opendict-apple/releases/download/appledict-v#{version}/OpenDictionary.dictionary.zip",
      verified: "github.com/wesleyel/opendict-apple/"
  name "Open Dictionary"
  name "Open Dictionary 英汉学习词典"
  desc "English-Chinese learner dictionary for Dictionary.app, built from Wiktionary"
  homepage "https://github.com/wesleyel/opendict-apple"

  livecheck do
    url :url
    regex(/^appledict[._-]v?(\d+(?:\.\d+)+)$/i)
    strategy :github_latest
  end

  depends_on macos: :catalina

  dictionary "Open Dictionary.dictionary"

  caveats <<~EOS
    Dictionary data is CC BY-SA 4.0, derived from Wiktionary via
    github.com/ahpxex/open-dictionary. Enable it in Dictionary.app > Settings.
  EOS
end
