#!/usr/bin/env python3
"""Regenerate Casks/open-dictionary.rb.

The cask is generated rather than hand-edited so the release tag, version and
checksum can never drift apart. CI runs this after uploading the release asset.

  python3 scripts/update_cask.py --repo owner/name --version 2.0 --sha256 <hex>
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re

TEMPLATE = '''# Generated by scripts/update_cask.py — do not edit by hand.
cask "open-dictionary" do
  version "{version}"
  sha256 "{sha256}"

  url "https://github.com/{repo}/releases/download/appledict-v#{{version}}/OpenDictionary.dictionary.zip",
      verified: "github.com/{repo}/"
  name "Open Dictionary"
  name "Open Dictionary 英汉学习词典"
  desc "English-Chinese learner dictionary for Dictionary.app, built from Wiktionary"
  homepage "https://github.com/{repo}"

  livecheck do
    url :url
    regex(/^appledict[._-]v?(\\d+(?:\\.\\d+)+)$/i)
    strategy :github_latest
  end

  depends_on macos: :catalina

  dictionary "Open Dictionary.dictionary"

  caveats <<~EOS
    Dictionary data is CC BY-SA 4.0, derived from Wiktionary via
    github.com/ahpxex/open-dictionary. Enable it in Dictionary.app > Settings.
  EOS
end
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, help="owner/name of the repo hosting the release")
    ap.add_argument("--version", required=True, help="version without the leading v, e.g. 2.0")
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--sha256", help="checksum of OpenDictionary.dictionary.zip")
    group.add_argument("--asset", help="path to the zip; its checksum is computed")
    ap.add_argument("-o", "--output", default="Casks/open-dictionary.rb")
    args = ap.parse_args()

    if args.asset:
        h = hashlib.sha256()
        with open(args.asset, "rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b""):
                h.update(chunk)
        digest = h.hexdigest()
    else:
        digest = args.sha256.strip().lower()

    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise SystemExit(f"not a sha256 digest: {digest!r}")
    version = args.version.lstrip("v")

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(repo=args.repo, version=version, sha256=digest), encoding="utf-8")
    print(f"wrote {out} (version={version} sha256={digest[:12]}…)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
