#!/usr/bin/env python3
"""Regenerate open-dictionary.rb (and the audio variant) for wesleyel/homebrew-tap.

The cask is generated rather than hand-edited so the release tag, version and
checksum can never drift apart. The publish job writes into a checkout of
wesleyel/homebrew-tap via --output.

Both variants install to the same path under ~/Library/Dictionaries, so they
declare each other in conflicts_with: they are alternatives, not companions.

  python3 scripts/update_cask.py --repo owner/name --version 2.0 --sha256 <hex> \\
      -o /path/to/homebrew-tap/Casks/open-dictionary.rb
  python3 scripts/update_cask.py --variant audio --repo owner/name \\
      --version 2.0 --asset OpenDictionary-audio.dictionary.zip \\
      -o /path/to/homebrew-tap/Casks/open-dictionary-audio.rb
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re

TEMPLATE = '''# Generated by scripts/update_cask.py — do not edit by hand.
cask "{token}" do
  version "{version}"
  sha256 "{sha256}"

  url "https://github.com/{repo}/releases/download/appledict-v#{{version}}/{asset}",
      verified: "github.com/{repo}/"
  name "Open Dictionary{name_suffix}"
  name "Open Dictionary 英汉学习词典{cn_suffix}"
  desc "{desc}"
  homepage "https://github.com/{repo}"

  livecheck do
    url :url
    regex(/^appledict[._-]v?(\\d+(?:\\.\\d+)+)$/i)
    strategy :github_latest
  end

  conflicts_with cask: "{conflicts}"
  depends_on macos: :catalina

  dictionary "Open Dictionary.dictionary"

  caveats <<~EOS
    Dictionary data is CC BY-SA 4.0, derived from Wiktionary via
    github.com/ahpxex/open-dictionary. Enable it in Dictionary.app > Settings.{audio_caveat}
  EOS
end
'''

# Both variants compile to the same bundle name and identifier, so Homebrew
# would otherwise let them overwrite each other silently.
VARIANTS = {
    "plain": {
        "token": "open-dictionary",
        "asset": "OpenDictionary.dictionary.zip",
        "name_suffix": "",
        "cn_suffix": "",
        "desc": "English-Chinese learner dictionary for Dictionary.app, built from Wiktionary",
        "conflicts": "open-dictionary-audio",
        "audio_caveat": "",
        "output": "Casks/open-dictionary.rb",
    },
    "audio": {
        "token": "open-dictionary-audio",
        "asset": "OpenDictionary-audio.dictionary.zip",
        "name_suffix": " with Audio",
        "cn_suffix": "（含发音）",
        "desc": "English-Chinese learner dictionary for Dictionary.app with bundled pronunciation",
        "conflicts": "open-dictionary",
        "audio_caveat": (
            "\n\n    Pronunciation clips are bundled, so playback works offline. The\n"
            "    play buttons need JavaScript, which Dictionary.app supports but the\n"
            "    three-finger lookup popover does not."
        ),
        "output": "Casks/open-dictionary-audio.rb",
    },
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, help="owner/name of the repo hosting the release")
    ap.add_argument("--version", required=True, help="version without the leading v, e.g. 2.0")
    ap.add_argument(
        "--variant",
        choices=sorted(VARIANTS),
        default="plain",
        help="which cask to write (default: plain)",
    )
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--sha256", help="checksum of the release zip")
    group.add_argument("--asset", help="path to the zip; its checksum is computed")
    ap.add_argument("-o", "--output", default="", help="override the cask path")
    args = ap.parse_args()

    variant = VARIANTS[args.variant]

    if args.asset:
        h = hashlib.sha256()
        with open(args.asset, "rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b""):
                h.update(chunk)
        digest = h.hexdigest()
    else:
        digest = args.sha256.strip().lower()

    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise SystemExit(f"not a sha256 digest: {digest!r}")
    version = args.version.lstrip("v")

    fields = {k: v for k, v in variant.items() if k != "output"}
    out = pathlib.Path(args.output or variant["output"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        TEMPLATE.format(repo=args.repo, version=version, sha256=digest, **fields),
        encoding="utf-8",
    )
    print(f"wrote {out} (version={version} sha256={digest[:12]}…)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
